allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true

ignoredBuiltDependencies:
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
